# Tensors:
Tensor is a specialized multi-dimensional array designed for mathematical and computational efficiency.
## Types of Tensors:

1. Scalar (0-D Tensor)

- Single value - just one number
- 0 dimensions - no axes/length
- Size: `torch.Size([])`
- Examples:
- Loss value (e.g., 0.456)
- Accuracy percentage
- Learning rate
- Temperature parameter

2. Vector (1-D Tensor)

- 1D array - sequence of numbers
- 1 dimension - one axis with length
- Size: `torch.Size([n])`
- Examples:
- Bias vector in neural networks
- Word embeddings
- Feature vector for one sample

3. Matrix (2-D Tensor)
- 2D grid - rows and columns
- 2 dimensions - two axes
- Size: `torch.Size([rows, cols])`
- Examples:
- Weight matrices in fully connected layers
- Grayscale image (height × width)
- Dataset table (samples × features)

4. 3-D Tensor
- 3D cube - depth, height, width
- 3 dimensions - three axes
- Size: `torch.Size([depth, height, width])`
- Examples:
- RGB image (3 × height × width)
- Time series data (sequence_length × features × batches)
- CNN feature maps

5. n-D Tensor
- Multi-dimensional arrays
- n dimensions - any number of axes
- Size: `torch.Size([dim1, dim2, ..., dim_n])`
- Examples:
- 5D: Video data (batch × frames × channels × height × width)
- Higher dimensions in complex models
## Forward Pass:
- Definition: The process of passing input data through a neural network to get predictions.

In [14]:
import torch
import numpy as np
print(torch.__version__)

2.9.0+cu126


In [2]:
import torch

# Method 1: Check if CUDA (GPU) is available
print("CUDA available:", torch.cuda.is_available())

# Method 2: Check number of available GPUs
print("Number of GPUs:", torch.cuda.device_count())

# Method 3: Get current device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Current device:", device)

# Method 4: Get GPU name (if available)
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("No GPU found, using CPU")

# Method 5: Check memory info (if GPU available)
if torch.cuda.is_available():
    print("GPU memory allocated:", torch.cuda.memory_allocated(0))
    print("GPU memory cached:", torch.cuda.memory_reserved(0))

CUDA available: False
Number of GPUs: 0
Current device: cpu
No GPU found, using CPU


# Creating Tensor

In [3]:
# using empty - Allocates memory
torch.empty(3, 4)

tensor([[1.6346e-38, 0.0000e+00, 1.6331e-38, 0.0000e+00],
        [1.6349e-38, 0.0000e+00, 1.6331e-38, 0.0000e+00],
        [1.7937e-43, 0.0000e+00, 6.7262e-44, 0.0000e+00]])

In [4]:
# Check type
type(torch.empty(3, 4))

torch.Tensor

In [7]:
# Creates a 2x3 tensor filled with zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# Using rand
torch.rand(2,3)

tensor([[0.0059, 0.9603, 0.9797],
        [0.3488, 0.7767, 0.5429]])

In [10]:
# Manual seed (Using rand but everytime you run u get one fixed random value)
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [12]:
# Custom tensor
torch.tensor([[1,2,3,4],[4,5,6,7]])

tensor([[1, 2, 3, 4],
        [4, 5, 6, 7]])

In [17]:
# Creates 2x3 tensor filled with 1s
torch.ones(2, 3)

# Creates 3x3 identity matrix (1s on diagonal, 0s elsewhere)
torch.eye(3)

# Creates tensor with random values between 0-1
torch.rand(2, 3)

# Creates tensor with random values from normal distribution
torch.randn(2, 3)

# Creates tensor with values from start to end-1
torch.arange(0, 5)  # [0, 1, 2, 3, 4]

# Creates tensor with equally spaced values
torch.linspace(0, 1, 5)  # [0.0, 0.25, 0.5, 0.75, 1.0]


tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

# Tensor Shapes

In [20]:
# First create a tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [21]:
# Get tensor shape/dimensions
x.shape  # Returns torch.Size([rows, cols])

torch.Size([2, 3])

In [22]:
# Get number of dimensions
x.ndim   # Returns integer (0 for scalar, 1 for vector, etc.)

2

In [23]:
# Get total number of elements
x.numel() # Returns product of all dimensions

6

In [25]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [26]:
print("Original shape:", x.shape)

Original shape: torch.Size([2, 3])


In [27]:
print("Reshape to 3x2:", x.reshape(3, 2))

Reshape to 3x2: tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [29]:
# View - similar to reshape but shares memory
x.view(6, 1)     # Reshapes without copying data

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [30]:
# Transpose - swap dimensions
x.T              # Swaps rows and columns

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [31]:
# Squeeze - remove dimensions of size 1
x.squeeze()      # Removes all singleton dimensions

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
# Unsqueeze - add dimension of size 1 at specified position
x.unsqueeze(0)   # Adds batch dimension at front

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [40]:
# Create sample tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# _like functions - create new tensors with same shape as input
print("Zeros like x:", torch.zeros_like(x))    # Same shape as x, all zeros
print("Ones like x:", torch.ones_like(x))      # Same shape as x, all ones
print("Rand like x:", torch.rand_like(x, dtype=torch.float32))      # Same shape as x, random values
print("Full like x:", torch.full_like(x, 7))   # Same shape as x, all 7s

# Useful for creating tensors matching dimensions of existing ones

Zeros like x: tensor([[0, 0, 0],
        [0, 0, 0]])
Ones like x: tensor([[1, 1, 1],
        [1, 1, 1]])
Rand like x: tensor([[0.6790, 0.9155, 0.2418],
        [0.1591, 0.7653, 0.2979]])
Full like x: tensor([[7, 7, 7],
        [7, 7, 7]])


# Tensor Data Types

In [35]:
# Find data type
x.dtype

torch.int64

In [36]:
# Assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [37]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [38]:
# Using to() -> Change data type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [39]:
x.dtype

torch.int64

# Mathematical Operations


In [41]:
# Create sample tensors
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Basic arithmetic
print("Addition:", a + b)           # Element-wise [5, 7, 9]
print("Subtraction:", a - b)        # Element-wise [-3, -3, -3]
print("Multiplication:", a * b)     # Element-wise [4, 10, 18]
print("Division:", a / b)           # Element-wise [0.25, 0.4, 0.5]

# Matrix multiplication
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
print("Matmul:", torch.matmul(x, y))  # [[19, 22], [43, 50]]

# Reduction operations
z = torch.tensor([[1, 2], [3, 4]])
print("Sum:", torch.sum(z))          # 10
print("Mean:", torch.mean(z.float())) # 2.5
print("Max:", torch.max(z))          # 4
print("Min:", torch.min(z))          # 1

Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])
Matmul: tensor([[19, 22],
        [43, 50]])
Sum: tensor(10)
Mean: tensor(2.5000)
Max: tensor(4)
Min: tensor(1)


In [42]:
# Create sample tensors
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# More mathematical operations
print("Power:", a ** 2)              # Element-wise square [1, 4, 9]
print("Square root:", torch.sqrt(a.float())) # [1.00, 1.41, 1.73]
print("Exponential:", torch.exp(a))  # [2.718, 7.389, 20.085]

# Comparison operations
print("Equal:", a == b)              # [False, False, False]
print("Greater than:", a > b)        # [False, False, False]
print("Less than or equal:", a <= b) # [True, True, True]

# Trigonometric functions
angles = torch.tensor([0, 30, 45, 60, 90])
radians = torch.deg2rad(angles)
print("Sin:", torch.sin(radians))    # Sine values

# Clamping values
x = torch.tensor([1, 5, 10, 15, 20])
print("Clamp 3-12:", torch.clamp(x, min=3, max=12)) # [3, 5, 10, 12, 12]

# Absolute values
neg = torch.tensor([-1, -2, 3, -4])
print("Absolute:", torch.abs(neg))   # [1, 2, 3, 4]

Power: tensor([1, 4, 9])
Square root: tensor([1.0000, 1.4142, 1.7321])
Exponential: tensor([ 2.7183,  7.3891, 20.0855])
Equal: tensor([False, False, False])
Greater than: tensor([False, False, False])
Less than or equal: tensor([True, True, True])
Sin: tensor([0.0000, 0.5000, 0.7071, 0.8660, 1.0000])
Clamp 3-12: tensor([ 3,  5, 10, 12, 12])
Absolute: tensor([1, 2, 3, 4])


In [43]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise: operations happen per corresponding element
print(a + b)  # [1+4, 2+5, 3+6] = [5, 7, 9]
print(a * b)  # [1*4, 2*5, 3*6] = [4, 10, 18]

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [44]:
x = torch.tensor([[1, 2], [3, 4]])  # 2x2
y = torch.tensor([[5, 6], [7, 8]])  # 2x2

# Matrix multiplication: dot product of rows and columns
print(x @ y)  # [[1*5+2*7, 1*6+2*8], [3*5+4*7, 3*6+4*8]] = [[19, 22], [43, 50]]

tensor([[19, 22],
        [43, 50]])


In [45]:
x = torch.tensor([3, 1, 4, 1, 5])

print("Tensor:", x)
print("argmax:", torch.argmax(x))  # Index of largest value: 4 (value 5)
print("argmin:", torch.argmin(x))  # Index of smallest value: 1 (value 1)

# Dot product (sum of element-wise multiplication)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("Dot product:", torch.dot(a, b))  # 1*4 + 2*5 + 3*6 = 32

Tensor: tensor([3, 1, 4, 1, 5])
argmax: tensor(4)
argmin: tensor(1)
Dot product: tensor(32)


In [46]:
# Create a square matrix (2x2)
A = torch.tensor([[4.0, 7.0], [2.0, 6.0]])

print("Matrix A:\n", A)

# Determinant
det = torch.det(A)
print("Determinant:", det)  # 4*6 - 7*2 = 24 - 14 = 10

# Inverse (only for square matrices with non-zero determinant)
inv = torch.inverse(A)
print("Inverse:\n", inv)  # [[0.6, -0.7], [-0.2, 0.4]]

# Verify: A * A⁻¹ = Identity matrix
identity = A @ inv
print("A * A⁻¹:\n", identity)  # Should be ~[[1, 0], [0, 1]]

Matrix A:
 tensor([[4., 7.],
        [2., 6.]])
Determinant: tensor(10.0000)
Inverse:
 tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]])
A * A⁻¹:
 tensor([[1., 0.],
        [0., 1.]])


# Inplace Operations:
- Inplace Operators are operations that modify the original tensor directly instead of creating a new one.
- Identified by underscore suffix `(_)` - `add_()`, `mul_()`, etc.

In [49]:
import pandas as pd
import numpy as np

# Get all rows where condition is FALSE
df = pd.DataFrame({'age': [25, 30, 35, 40]})
mask = df['age'] > 30
print(~mask)  # [True, True, False, False] - INVERTS the boolean mask

0     True
1     True
2    False
3    False
Name: age, dtype: bool


In [50]:
# Regular operation - creates new tensor, original unchanged
x = torch.tensor([1, 2, 3])
y = x + 1  # Creates new tensor y, x remains same
print("Original x:", x)  # [1, 2, 3]
print("New tensor y:", y)  # [2, 3, 4]
print("x ID:", id(x), "y ID:", id(y))  # Different memory addresses

Original x: tensor([1, 2, 3])
New tensor y: tensor([2, 3, 4])
x ID: 134263795137936 y ID: 134263795137376


In [51]:
# Cell 2: Inplace add operation
x = torch.tensor([1, 2, 3])
x.add_(1)  # add_ modifies x directly (inplace)
print("After add_:", x)  # [2, 3, 4] - x is changed
# Memory efficient but be careful with gradients!

After add_: tensor([2, 3, 4])


In [54]:
# Cell 3: Inplace multiply
x = torch.tensor([1, 2, 3])
x.mul_(2)  # mul_ multiplies each element by 2 inplace
print("After mul_:", x)  # [2, 4, 6]
# Equivalent to x *= 2 but modifies original

After mul_: tensor([2, 4, 6])


In [53]:
# Clone
original = torch.tensor([1, 2, 3])
copy = original.clone()  # Creates exact copy

# Tensor Operation in GPU

In [2]:
import torch
# Move tensor to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
# Create tensor on GPU directly
x = torch.tensor([1, 2, 3], device=device)  # On GPU
y = torch.tensor([4, 5, 6], device=device)  # On GPU

In [4]:
# Or move CPU tensor to GPU
z = torch.tensor([7, 8, 9])
z = z.to(device)  # Move to GPU

In [5]:
# Operations happen on GPU (much faster!)
result = x + y * z
print("GPU result:", result)

GPU result: tensor([29, 42, 57], device='cuda:0')


In [6]:
# Move back to CPU for numpy conversion
result_cpu = result.cpu()